<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['title' => 'Andorra','iso' => 'AD','area_code' => '+376'],
            ['title' => 'United Arab Emirates','iso' => 'AE','area_code' => '+971'],
            ['title' => 'Afghanistan','iso' => 'AF','area_code' => '+93'],
            ['title' => 'Anguilla','iso' => 'AI','area_code' => '+1264'],
            ['title' => 'Albania','iso' => 'AL','area_code' => '+355'],
            ['title' => 'Armenia','iso' => 'AM','area_code' => '+374'],
            ['title' => 'Angola','iso' => 'AO','area_code' => '+244'],
            ['title' => 'Argentina','iso' => 'AR','area_code' => '+54'],
            ['title' => 'Austria','iso' => 'AT','area_code' => '+43'],
            ['title' => 'Australia','iso' => 'AU','area_code' => '+61'],
            ['title' => 'Aruba','iso' => 'AW','area_code' => '+297'],
            ['title' => 'Azerbaijan','iso' => 'AZ','area_code' => '+994'],
            ['title' => 'Barbados','iso' => 'BB','area_code' => '+1246'],
            ['title' => 'Bangladesh','iso' => 'BD','area_code' => '+880'],
            ['title' => 'Belgium','iso' => 'BE','area_code' => '+32'],
            ['title' => 'Burkina Faso','iso' => 'BF','area_code' => '+226'],
            ['title' => 'Bulgaria','iso' => 'BG','area_code' => '+359'],
            ['title' => 'Bahrain','iso' => 'BH','area_code' => '+973'],
            ['title' => 'Burundi','iso' => 'BI','area_code' => '+257'],
            ['title' => 'Benin','iso' => 'BJ','area_code' => '+229'],
            ['title' => 'Bermuda','iso' => 'BM','area_code' => '+1441'],
            ['title' => 'Bolivia','iso' => 'BO','area_code' => '+591'],
            ['title' => 'Brazil','iso' => 'BR','area_code' => '+55'],
            ['title' => 'Bhutan','iso' => 'BT','area_code' => '+975'],
            ['title' => 'Botswana','iso' => 'BW','area_code' => '+267'],
            ['title' => 'Belarus','iso' => 'BY','area_code' => '+375'],
            ['title' => 'Belize','iso' => 'BZ','area_code' => '+501'],
            ['title' => 'Canada','iso' => 'CA','area_code' => '+1'],
            ['title' => 'Central African Republic','iso' => 'CF','area_code' => '+236'],
            ['title' => 'Congo','iso' => 'CG','area_code' => '+242'],
            ['title' => 'Switzerland','iso' => 'CH','area_code' => '+41'],
            ['title' => 'Cook Islands','iso' => 'CK','area_code' => '+682'],
            ['title' => 'Chile','iso' => 'CL','area_code' => '+56'],
            ['title' => 'Cameroon','iso' => 'CM','area_code' => '+237'],
            ['title' => 'China','iso' => 'CN','area_code' => '+86'],
            ['title' => 'Colombia','iso' => 'CO','area_code' => '+57'],
            ['title' => 'Costa Rica','iso' => 'CR','area_code' => '+506'],
            ['title' => 'Cuba','iso' => 'CU','area_code' => '+53'],
            ['title' => 'Cape Verde','iso' => 'CV','area_code' => '+238'],
            ['title' => 'Curaçao','iso' => 'CW','area_code' => '+5999'],
            ['title' => 'Cyprus','iso' => 'CY','area_code' => '+357'],
            ['title' => 'Czech Republic','iso' => 'CZ','area_code' => '+420'],
            ['title' => 'Germany','iso' => 'DE','area_code' => '+49'],
            ['title' => 'Djibouti','iso' => 'DJ','area_code' => '+253'],
            ['title' => 'Denmark','iso' => 'DK','area_code' => '+45'],
            ['title' => 'Dominica','iso' => 'DM','area_code' => '+1767'],
            ['title' => 'Dominican Republic','iso' => 'DO','area_code' => '+1'],
            ['title' => 'Algeria','iso' => 'DZ','area_code' => '+213'],
            ['title' => 'Ecuador','iso' => 'EC','area_code' => '+593'],
            ['title' => 'Estonia','iso' => 'EE','area_code' => '+372'],
            ['title' => 'Egypt','iso' => 'EG','area_code' => '+20'],
            ['title' => 'Spain','iso' => 'ES','area_code' => '+34'],
            ['title' => 'Ethiopia','iso' => 'ET','area_code' => '+251'],
            ['title' => 'Finland','iso' => 'FI','area_code' => '+358'],
            ['title' => 'Fiji','iso' => 'FJ','area_code' => '+679'],
            ['title' => 'Falkland Islands','iso' => 'FK','area_code' => '+500'],
            ['title' => 'Faroe Islands','iso' => 'FO','area_code' => '+298'],
            ['title' => 'France','iso' => 'FR','area_code' => '+33'],
            ['title' => 'Gabon','iso' => 'GA','area_code' => '+241'],
            ['title' => 'United Kingdom','iso' => 'GB','area_code' => '+44'],
            ['title' => 'Grenada','iso' => 'GD','area_code' => '+1473'],
            ['title' => 'Georgia','iso' => 'GE','area_code' => '+995'],
            ['title' => 'French Guiana','iso' => 'GF','area_code' => '+594'],
            ['title' => 'Guernsey','iso' => 'GG','area_code' => '+44'],
            ['title' => 'Ghana','iso' => 'GH','area_code' => '+233'],
            ['title' => 'Gibraltar','iso' => 'GI','area_code' => '+350'],
            ['title' => 'Greenland','iso' => 'GL','area_code' => '+299'],
            ['title' => 'Gambia','iso' => 'GM','area_code' => '+220'],
            ['title' => 'Guinea','iso' => 'GN','area_code' => '+224'],
            ['title' => 'Guadeloupe','iso' => 'GP','area_code' => '+590'],
            ['title' => 'Equatorial Guinea','iso' => 'GQ','area_code' => '+240'],
            ['title' => 'Greece','iso' => 'GR','area_code' => '+30'],
            ['title' => 'Guatemala','iso' => 'GT','area_code' => '+502'],
            ['title' => 'Guam','iso' => 'GU','area_code' => '+1671'],
            ['title' => 'Guyana','iso' => 'GY','area_code' => '+592'],
            ['title' => 'Honduras','iso' => 'HN','area_code' => '+504'],
            ['title' => 'Croatia','iso' => 'HR','area_code' => '+385'],
            ['title' => 'Haiti','iso' => 'HT','area_code' => '+509'],
            ['title' => 'Hungary','iso' => 'HU','area_code' => '+36'],
            ['title' => 'Indonesia','iso' => 'ID','area_code' => '+62'],
            ['title' => 'Ireland','iso' => 'IE','area_code' => '+353'],
            ['title' => 'Israel','iso' => 'IL','area_code' => '+972'],
            ['title' => 'Isle of Man','iso' => 'IM','area_code' => '+44'],
            ['title' => 'India','iso' => 'IN','area_code' => '+91'],
            ['title' => 'Iraq','iso' => 'IQ','area_code' => '+964'],
            ['title' => 'Iran','iso' => 'IR','area_code' => '+98'],
            ['title' => 'Iceland','iso' => 'IS','area_code' => '+354'],
            ['title' => 'Italy','iso' => 'IT','area_code' => '+39'],
            ['title' => 'Jersey','iso' => 'JE','area_code' => '+44'],
            ['title' => 'Jamaica','iso' => 'JM','area_code' => '+1876'],
            ['title' => 'Jordan','iso' => 'JO','area_code' => '+962'],
            ['title' => 'Japan','iso' => 'JP','area_code' => '+81'],
            ['title' => 'Kenya','iso' => 'KE','area_code' => '+254'],
            ['title' => 'Kyrgyzstan','iso' => 'KG','area_code' => '+996'],
            ['title' => 'Cambodia','iso' => 'KH','area_code' => '+855'],
            ['title' => 'Comoros','iso' => 'KM','area_code' => '+269'],
            ['title' => 'Kuwait','iso' => 'KW','area_code' => '+965'],
            ['title' => 'Cayman Islands','iso' => 'KY','area_code' => '+1345'],
            ['title' => 'Kazakhstan','iso' => 'KZ','area_code' => '+7'],
            ['title' => 'Lebanon','iso' => 'LB','area_code' => '+961'],
            ['title' => 'Liechtenstein','iso' => 'LI','area_code' => '+423'],
            ['title' => 'Sri Lanka','iso' => 'LK','area_code' => '+94'],
            ['title' => 'Liberia','iso' => 'LR','area_code' => '+231'],
            ['title' => 'Lesotho','iso' => 'LS','area_code' => '+266'],
            ['title' => 'Lithuania','iso' => 'LT','area_code' => '+370'],
            ['title' => 'Luxembourg','iso' => 'LU','area_code' => '+352'],
            ['title' => 'Latvia','iso' => 'LV','area_code' => '+371'],
            ['title' => 'Libya','iso' => 'LY','area_code' => '+218'],
            ['title' => 'Morocco','iso' => 'MA','area_code' => '+212'],
            ['title' => 'Moldova','iso' => 'MD','area_code' => '+373'],
            ['title' => 'Montenegro','iso' => 'ME','area_code' => '+382'],
            ['title' => 'Madagascar','iso' => 'MG','area_code' => '+261'],
            ['title' => 'Macedonia','iso' => 'MK','area_code' => '+389'],
            ['title' => 'Mali','iso' => 'ML','area_code' => '+223'],
            ['title' => 'Myanmar','iso' => 'MM','area_code' => '+95'],
            ['title' => 'Mongolia','iso' => 'MN','area_code' => '+976'],
            ['title' => 'Macau','iso' => 'MO','area_code' => '+853'],
            ['title' => 'Martinique','iso' => 'MQ','area_code' => '+596'],
            ['title' => 'Mauritania','iso' => 'MR','area_code' => '+222'],
            ['title' => 'Montserrat','iso' => 'MS','area_code' => '+1664'],
            ['title' => 'Malta','iso' => 'MT','area_code' => '+356'],
            ['title' => 'Mauritius','iso' => 'MU','area_code' => '+230'],
            ['title' => 'Maldives','iso' => 'MV','area_code' => '+960'],
            ['title' => 'Malawi','iso' => 'MW','area_code' => '+265'],
            ['title' => 'Mexico','iso' => 'MX','area_code' => '+52'],
            ['title' => 'Malaysia','iso' => 'MY','area_code' => '+60'],
            ['title' => 'Mozambique','iso' => 'MZ','area_code' => '+258'],
            ['title' => 'Namibia','iso' => 'NA','area_code' => '+264'],
            ['title' => 'New Caledonia','iso' => 'NC','area_code' => '+687'],
            ['title' => 'Niger','iso' => 'NE','area_code' => '+227'],
            ['title' => 'Nigeria','iso' => 'NG','area_code' => '+234'],
            ['title' => 'Nicaragua','iso' => 'NI','area_code' => '+505'],
            ['title' => 'Norway','iso' => 'NO','area_code' => '+47'],
            ['title' => 'Nepal','iso' => 'NP','area_code' => '+977'],
            ['title' => 'Nauru','iso' => 'NR','area_code' => '+674'],
            ['title' => 'New Zealand','iso' => 'NZ','area_code' => '+64'],
            ['title' => 'Oman','iso' => 'OM','area_code' => '+968'],
            ['title' => 'Panama','iso' => 'PA','area_code' => '+507'],
            ['title' => 'Peru','iso' => 'PE','area_code' => '+51'],
            ['title' => 'French Polynesia','iso' => 'PF','area_code' => '+689'],
            ['title' => 'Papua New Guinea','iso' => 'PG','area_code' => '+675'],
            ['title' => 'Philippines','iso' => 'PH','area_code' => '+63'],
            ['title' => 'Pakistan','iso' => 'PK','area_code' => '+92'],
            ['title' => 'Poland','iso' => 'PL','area_code' => '+48'],
            ['title' => 'Puerto Rico','iso' => 'PR','area_code' => '+1'],
            ['title' => 'Portugal','iso' => 'PT','area_code' => '+351'],
            ['title' => 'Paraguay','iso' => 'PY','area_code' => '+595'],
            ['title' => 'Qatar','iso' => 'QA','area_code' => '+974'],
            ['title' => 'Réunion','iso' => 'RE','area_code' => '+262'],
            ['title' => 'Romania','iso' => 'RO','area_code' => '+40'],
            ['title' => 'Serbia','iso' => 'RS','area_code' => '+381'],
            ['title' => 'Rwanda','iso' => 'RW','area_code' => '+250'],
            ['title' => 'Saudi Arabia','iso' => 'SA','area_code' => '+966'],
            ['title' => 'Solomon Islands','iso' => 'SB','area_code' => '+677'],
            ['title' => 'Seychelles','iso' => 'SC','area_code' => '+248'],
            ['title' => 'Sudan','iso' => 'SD','area_code' => '+249'],
            ['title' => 'Sweden','iso' => 'SE','area_code' => '+46'],
            ['title' => 'Singapore','iso' => 'SG','area_code' => '+65'],
            ['title' => 'Slovenia','iso' => 'SI','area_code' => '+386'],
            ['title' => 'Slovakia','iso' => 'SK','area_code' => '+421'],
            ['title' => 'Sierra Leone','iso' => 'SL','area_code' => '+232'],
            ['title' => 'San Marino','iso' => 'SM','area_code' => '+378'],
            ['title' => 'Senegal','iso' => 'SN','area_code' => '+221'],
            ['title' => 'Somalia','iso' => 'SO','area_code' => '+252'],
            ['title' => 'Suriname','iso' => 'SR','area_code' => '+597'],
            ['title' => 'El Salvador','iso' => 'SV','area_code' => '+503'],
            ['title' => 'Syria','iso' => 'SY','area_code' => '+963'],
            ['title' => 'Swaziland','iso' => 'SZ','area_code' => '+268'],
            ['title' => 'Turks and Caicos Islands','iso' => 'TC','area_code' => '+1649'],
            ['title' => 'Chad','iso' => 'TD','area_code' => '+235'],
            ['title' => 'Togo','iso' => 'TG','area_code' => '+228'],
            ['title' => 'Thailand','iso' => 'TH','area_code' => '+66'],
            ['title' => 'Tajikistan','iso' => 'TJ','area_code' => '+992'],
            ['title' => 'Turkmenistan','iso' => 'TM','area_code' => '+993'],
            ['title' => 'Tunisia','iso' => 'TN','area_code' => '+216'],
            ['title' => 'Turkey','iso' => 'TR','area_code' => '+90'],
            ['title' => 'Trinidad and Tobago','iso' => 'TT','area_code' => '+1868'],
            ['title' => 'Taiwan','iso' => 'TW','area_code' => '+886'],
            ['title' => 'Tanzania','iso' => 'TZ','area_code' => '+255'],
            ['title' => 'Ukraine','iso' => 'UA','area_code' => '+380'],
            ['title' => 'Uganda','iso' => 'UG','area_code' => '+256'],
            ['title' => 'United States','iso' => 'US','area_code' => '+1'],
            ['title' => 'Uruguay','iso' => 'UY','area_code' => '+598'],
            ['title' => 'Uzbekistan','iso' => 'UZ','area_code' => '+998'],
            ['title' => 'Venezuela','iso' => 'VE','area_code' => '+58'],
            ['title' => 'Vietnam','iso' => 'VN','area_code' => '+84'],
            ['title' => 'Vanuatu','iso' => 'VU','area_code' => '+678'],
            ['title' => 'Yemen','iso' => 'YE','area_code' => '+967'],
            ['title' => 'South Africa','iso' => 'ZA','area_code' => '+27'],
            ['title' => 'Zambia','iso' => 'ZM','area_code' => '+260'],
            ['title' => 'Zimbabwe','iso' => 'ZW','area_code' => '+263']
        ];

        foreach ($countries as $countryData) {
            Country::factory()->create($countryData);
        }
    }
}



