<?php

namespace Database\Seeders;

use App\Models\Location;
use App\Models\Region;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $locations = [
            ['region' => 'Autres','title' => 'Autres','slug' => 'autres'],
            ['region' => 'Dakar','title' => 'Biscuiterie','slug' => 'biscuiterie'],
            ['region' => 'Dakar','title' => 'Cambérène','slug' => 'camberene'],
            ['region' => 'Dakar','title' => 'Dieuppeul Derklé','slug' => 'dieuppeul-derkle'],
            ['region' => 'Dakar','title' => 'Fann Point-E Amitié','slug' => 'fann-point-e-amitie'],
            ['region' => 'Dakar','title' => 'Gorée','slug' => 'goree'],
            ['region' => 'Dakar','title' => 'Grand-Dakar','slug' => 'grand-dakar'],
            ['region' => 'Dakar','title' => 'Grand-Yoff','slug' => 'grand-yoff'],
            ['region' => 'Dakar','title' => 'Guediawaye','slug' => 'guediawaye'],
            ['region' => 'Dakar','title' => 'Gueule-Tapée, Fass, Colobane','slug' => 'gueule-tapee-fass-colobane'],
            ['region' => 'Dakar','title' => 'Hann Bel-Air','slug' => 'hann-bel-air'],
            ['region' => 'Dakar','title' => 'Hlm','slug' => 'hlm'],
            ['region' => 'Dakar','title' => 'Médina','slug' => 'medina'],
            ['region' => 'Dakar','title' => 'Mermoz Sacré-Cœur','slug' => 'mermoz-sacre-coeur'],
            ['region' => 'Dakar','title' => 'Ngor','slug' => 'ngor'],
            ['region' => 'Dakar','title' => 'Ouakam','slug' => 'ouakam'],
            ['region' => 'Dakar','title' => 'Parcelles Assainies','slug' => 'parcelles-assainies'],
            ['region' => 'Dakar','title' => "Patte d'oie",'slug' => 'patte-doie'],
            ['region' => 'Dakar','title' => 'Pikine','slug' => 'pikine'],
            ['region' => 'Dakar','title' => 'Plateau','slug' => 'plateau'],
            ['region' => 'Dakar','title' => 'Rufisque','slug' => 'rufisque'],
            ['region' => 'Dakar','title' => 'Sicap Liberté','slug' => 'sicap-liberte'],
            ['region' => 'Dakar','title' => 'Yoff','slug' => 'yoff'],
            ['region' => 'Diourbel','title' => 'Bambey','slug' => 'bambey'],
            ['region' => 'Diourbel','title' => 'Diourbel','slug' => 'diourbel'],
            ['region' => 'Diourbel','title' => 'Mbacke','slug' => 'mbacke'],
            ['region' => 'Fatick','title' => 'Diofior','slug' => 'diofior'],
            ['region' => 'Fatick','title' => 'Fatick','slug' => 'fatick'],
            ['region' => 'Fatick','title' => 'Foundiougne','slug' => 'foundiougne'],
            ['region' => 'Fatick','title' => 'Gossas','slug' => 'gossas'],
            ['region' => 'Fatick','title' => 'Karang Poste','slug' => 'karang-poste'],
            ['region' => 'Fatick','title' => 'Passi','slug' => 'passi'],
            ['region' => 'Fatick','title' => 'Sokone','slug' => 'sokone'],
            ['region' => 'Fatick','title' => 'Soum','slug' => 'soum'],
            ['region' => 'Kaffrine','title' => 'Birkilane','slug' => 'birkilane'],
            ['region' => 'Kaffrine','title' => 'Kaffrine','slug' => 'kaffrine'],
            ['region' => 'Kaffrine','title' => 'Koungheul','slug' => 'koungheul'],
            ['region' => 'Kaffrine','title' => 'Mabo','slug' => 'mabo'],
            ['region' => 'Kaffrine','title' => 'Malem Hodar','slug' => 'malem-hodar'],
            ['region' => 'Kaffrine','title' => 'Nganda','slug' => 'nganda'],
            ['region' => 'Kaolack','title' => 'Fass','slug' => 'fass'],
            ['region' => 'Kaolack','title' => 'Gandiaye','slug' => 'gandiaye'],
            ['region' => 'Kaolack','title' => 'Guinguineo','slug' => 'guinguineo'],
            ['region' => 'Kaolack','title' => 'Kahone','slug' => 'kahone'],
            ['region' => 'Kaolack','title' => 'Kaolack','slug' => 'kaolack'],
            ['region' => 'Kaolack','title' => 'Keur Madiabel','slug' => 'keur-madiabel'],
            ['region' => 'Kaolack','title' => 'Mboss','slug' => 'mboss'],
            ['region' => 'Kaolack','title' => 'Ndoffane','slug' => 'ndoffane'],
            ['region' => 'Kaolack','title' => 'Nioro Du Rip','slug' => 'nioro-du-rip'],
            ['region' => 'Kaolack','title' => 'Sibassor','slug' => 'sibassor'],
            ['region' => 'Kedougou','title' => 'Kedougou','slug' => 'kedougou'],
            ['region' => 'Kedougou','title' => 'Salemata','slug' => 'salemata'],
            ['region' => 'Kedougou','title' => 'Saraya','slug' => 'saraya'],
            ['region' => 'Kolda','title' => 'Dabo','slug' => 'dabo'],
            ['region' => 'Kolda','title' => 'Diaobe Kabendou','slug' => 'diaobe-kabendou'],
            ['region' => 'Kolda','title' => 'Kolda','slug' => 'kolda'],
            ['region' => 'Kolda','title' => 'Kounkane','slug' => 'kounkane'],
            ['region' => 'Kolda','title' => 'Medina Yoro Foulah','slug' => 'medina-yoro-foulah'],
            ['region' => 'Kolda','title' => 'Pata','slug' => 'pata'],
            ['region' => 'Kolda','title' => 'Salikegne','slug' => 'salikegne'],
            ['region' => 'Kolda','title' => 'Sare Yoba Diega','slug' => 'sare-yoba-diega'],
            ['region' => 'Kolda','title' => 'Velingara','slug' => 'velingara'],
            ['region' => 'Louga','title' => 'Dahra','slug' => 'dahra'],
            ['region' => 'Louga','title' => 'Gueoul','slug' => 'gueoul'],
            ['region' => 'Louga','title' => 'Kebemer','slug' => 'kebemer'],
            ['region' => 'Louga','title' => 'Leona','slug' => 'leona'],
            ['region' => 'Louga','title' => 'Linguere','slug' => 'linguere'],
            ['region' => 'Louga','title' => 'Louga','slug' => 'louga'],
            ['region' => 'Louga','title' => 'Mbeuleukhe','slug' => 'mbeuleukhe'],
            ['region' => 'Louga','title' => 'Ngueune Sarr','slug' => 'ngueune-sarr'],
            ['region' => 'Louga','title' => 'Sakal','slug' => 'sakal'],
            ['region' => 'Louga','title' => 'Thiep','slug' => 'thiep'],
            ['region' => 'Matam','title' => 'Dembancane','slug' => 'dembancane'],
            ['region' => 'Matam','title' => 'Hamadi Hounare','slug' => 'hamadi-hounare'],
            ['region' => 'Matam','title' => 'Kanel','slug' => 'kanel'],
            ['region' => 'Matam','title' => 'Matam','slug' => 'matam'],
            ['region' => 'Matam','title' => 'Nguidjilone','slug' => 'nguidjilone'],
            ['region' => 'Matam','title' => 'Odobere','slug' => 'odobere'],
            ['region' => 'Matam','title' => 'Ouaounde','slug' => 'ouaounde'],
            ['region' => 'Matam','title' => 'Ourossogui','slug' => 'ourossogui'],
            ['region' => 'Matam','title' => 'Ranerou','slug' => 'ranerou'],
            ['region' => 'Matam','title' => 'Semme','slug' => 'semme'],
            ['region' => 'Matam','title' => 'Sinthiou Bamambe Banadji','slug' => 'sinthiou-bamambe-banadji'],
            ['region' => 'Matam','title' => 'Thilogne','slug' => 'thilogne'],
            ['region' => 'Sédhiou','title' => 'Bounkiling','slug' => 'bounkiling'],
            ['region' => 'Sédhiou','title' => 'Dianah Malary','slug' => 'dianah-malary'],
            ['region' => 'Sédhiou','title' => 'Diattacounda','slug' => 'diattacounda'],
            ['region' => 'Sédhiou','title' => 'Dioudoubou','slug' => 'dioudoubou'],
            ['region' => 'Sédhiou','title' => 'Djinany','slug' => 'djinany'],
            ['region' => 'Sédhiou','title' => 'Goudomp','slug' => 'goudomp'],
            ['region' => 'Sédhiou','title' => 'Kaour','slug' => 'kaour'],
            ['region' => 'Sédhiou','title' => 'Madina Wandifa','slug' => 'madina-wandifa'],
            ['region' => 'Sédhiou','title' => 'Marssassoum','slug' => 'marssassoum'],
            ['region' => 'Sédhiou','title' => 'Ndiamalathiel','slug' => 'ndiamalathiel'],
            ['region' => 'Sédhiou','title' => 'Sédhiou','slug' => 'sedhiou'],
            ['region' => 'Sédhiou','title' => 'Samine','slug' => 'samine'],
            ['region' => 'Sédhiou','title' => 'Simbandi Brassou','slug' => 'simbandi-brassou'],
            ['region' => 'Sédhiou','title' => 'Tanaff','slug' => 'tanaff'],
            ['region' => 'Saint-Louis','title' => 'Aere Lao','slug' => 'aere-lao'],
            ['region' => 'Saint-Louis','title' => 'Bode Lao','slug' => 'bode-lao'],
            ['region' => 'Saint-Louis','title' => 'Dagana','slug' => 'dagana'],
            ['region' => 'Saint-Louis','title' => 'Demette','slug' => 'demette'],
            ['region' => 'Saint-Louis','title' => 'Gae','slug' => 'gae'],
            ['region' => 'Saint-Louis','title' => 'Galoya Toucouleur','slug' => 'galoya-toucouleur'],
            ['region' => 'Saint-Louis','title' => 'Gnith','slug' => 'gnith'],
            ['region' => 'Saint-Louis','title' => 'Gollere','slug' => 'gollere'],
            ['region' => 'Saint-Louis','title' => 'Guede Chantier','slug' => 'guede-chantier'],
            ['region' => 'Saint-Louis','title' => 'Mboumba','slug' => 'mboumba'],
            ['region' => 'Saint-Louis','title' => 'Mpal','slug' => 'mpal'],
            ['region' => 'Saint-Louis','title' => 'Ndioum','slug' => 'ndioum'],
            ['region' => 'Saint-Louis','title' => 'Ndombo Sandjiry','slug' => 'ndombo-sandjiry'],
            ['region' => 'Saint-Louis','title' => 'Niandane','slug' => 'niandane'],
            ['region' => 'Saint-Louis','title' => 'Pete','slug' => 'pete'],
            ['region' => 'Saint-Louis','title' => 'Podor','slug' => 'podor'],
            ['region' => 'Saint-Louis','title' => 'Richard Toll','slug' => 'richard-toll'],
            ['region' => 'Saint-Louis','title' => 'Ross Bethio','slug' => 'ross-bethio'],
            ['region' => 'Saint-Louis','title' => 'Rosso Senegal','slug' => 'rosso-senegal'],
            ['region' => 'Saint-Louis','title' => 'Saint-Louis','slug' => 'saint-louis'],
            ['region' => 'Saint-Louis','title' => 'Walalde','slug' => 'walalde'],
            ['region' => 'Tambacounda','title' => 'Bakel','slug' => 'bakel'],
            ['region' => 'Tambacounda','title' => 'Diawara','slug' => 'diawara'],
            ['region' => 'Tambacounda','title' => 'Goudiry','slug' => 'goudiry'],
            ['region' => 'Tambacounda','title' => 'Kidira','slug' => 'kidira'],
            ['region' => 'Tambacounda','title' => 'Kothiary','slug' => 'kothiary'],
            ['region' => 'Tambacounda','title' => 'Koumpentoum','slug' => 'koumpentoum'],
            ['region' => 'Tambacounda','title' => 'Maleme Niani','slug' => 'maleme-niani'],
            ['region' => 'Tambacounda','title' => 'Mereto','slug' => 'mereto'],
            ['region' => 'Tambacounda','title' => 'Tambacounda','slug' => 'tambacounda'],
            ['region' => 'Thiès','title' => 'Guereo','slug' => 'guereo'],
            ['region' => 'Thiès','title' => 'Joal Fadiouth','slug' => 'joal-fadiouth'],
            ['region' => 'Thiès','title' => 'Kayar','slug' => 'kayar'],
            ['region' => 'Thiès','title' => 'Khombole','slug' => 'khombole'],
            ['region' => 'Thiès','title' => 'Mbodiene','slug' => 'mbodiene'],
            ['region' => 'Thiès','title' => 'Mboro','slug' => 'mboro'],
            ['region' => 'Thiès','title' => 'Mbour','slug' => 'mbour'],
            ['region' => 'Thiès','title' => 'Meckhe','slug' => 'meckhe'],
            ['region' => 'Thiès','title' => 'Ngaparou','slug' => 'ngaparou'],
            ['region' => 'Thiès','title' => 'Nguekhokh','slug' => 'nguekhokh'],
            ['region' => 'Thiès','title' => 'Nguering','slug' => 'nguering'],
            ['region' => 'Thiès','title' => 'Nianing','slug' => 'nianing'],
            ['region' => 'Thiès','title' => 'Pambal','slug' => 'pambal'],
            ['region' => 'Thiès','title' => 'Pointe Sarene','slug' => 'pointe-sarene'],
            ['region' => 'Thiès','title' => 'Popenguine','slug' => 'popenguine'],
            ['region' => 'Thiès','title' => 'Pout','slug' => 'pout'],
            ['region' => 'Thiès','title' => 'Saly Portudal','slug' => 'saly-portudal'],
            ['region' => 'Thiès','title' => 'Sandiara','slug' => 'sandiara'],
            ['region' => 'Thiès','title' => 'Somone','slug' => 'somone'],
            ['region' => 'Thiès','title' => 'Thiès','slug' => 'thies'],
            ['region' => 'Thiès','title' => 'Thiadiaye','slug' => 'thiadiaye'],
            ['region' => 'Thiès','title' => 'Tivaouane','slug' => 'tivaouane'],
            ['region' => 'Thiès','title' => 'Toubab Dialaw','slug' => 'toubab-dialaw'],
            ['region' => 'Thiès','title' => 'Warang','slug' => 'warang'],
            ['region' => 'Ziguinchor','title' => 'Bignona','slug' => 'bignona'],
            ['region' => 'Ziguinchor','title' => 'Diouloulou','slug' => 'diouloulou'],
            ['region' => 'Ziguinchor','title' => 'Oussouye','slug' => 'oussouye'],
            ['region' => 'Ziguinchor','title' => 'Thionck Essyl','slug' => 'thionck-essyl'],
            ['region' => 'Ziguinchor','title' => 'Ziguinchor','slug' => 'ziguinchor']
        ];

        foreach ($locations as $location) {
            Location::factory()->create([
                'title' => $location['title'],
                'slug' => $location['slug'],
                'region_id' => Region::where(['title' => $location['region']])->first()->id
            ]);
        }
    }
}
